import type { en } from './en'

export const zhCN: Record<keyof typeof en, string> = {
  'language.toggle': 'EN',
  'mode.aria': 'Workbench 模式',
  'mode.run': '运行', 'mode.studio': '工作室',
  'nav.sessions': '会话', 'nav.cases': '案例', 'nav.newSession': '新建会话', 'nav.newCase': '新建案例', 'nav.noSessions': '暂无已配置会话', 'nav.subagent': '子智能体', 'nav.facts': '{count} 条事件', 'nav.projectSettings': '项目设置', 'nav.runtimeReady': '运行时就绪',
  'header.noSession': '未选择会话', 'header.openInspector': '打开检查器',
  'run.offline': '离线', 'run.context': '上下文', 'run.unknown': '未知', 'run.lastOutput': '最近输出', 'run.outputRate': '输出速率', 'run.outputRateHint': '输出 Token 数除以 llm.invoke 到 llm.generated 的耗时', 'run.liveSession': '实时会话', 'run.completedSession': '已完成会话', 'run.selectSession': '请选择会话', 'run.liveDescription': '命令会推动持久化 Journal，右侧检查器展示其事件。', 'run.completedDescription': '这个已完成的 Journal 可供只读检查。', 'run.you': '你', 'run.reasoning': '思考', 'run.generating': '生成中', 'run.liveReasoning': '实时思考 · {count} 字符', 'run.additionalChars': '… 另有 {count} 个字符未渲染', 'run.running': '运行中', 'run.waitingOutput': '（等待输出）', 'run.noOutput': '（无输出）', 'run.result': '结果', 'run.todo': '待办', 'run.goal': '目标', 'run.allowTool': '允许执行 {tool}？', 'run.waiting': '另有 {count} 项等待处理', 'run.typeAnswer': '填写其他回答', 'run.deny': '拒绝', 'run.allow': '允许', 'run.answer': '回答', 'run.other': '其他…', 'run.askPlaceholder': '让 Knot 检查或修改工作区…', 'run.readOnlyPlaceholder': '此会话为只读', 'run.messageAria': '输入消息。Enter 发送，Shift+Enter 换行。', 'run.steerNow': '立即引导', 'run.followUp': '稍后跟进', 'run.newTurn': '新一轮', 'run.files': '@ 文件', 'run.resume': '继续', 'run.pause': '暂停', 'run.inputHint': 'Enter 发送 · Shift+Enter 换行 · 完整事件会提交到 JSONL', 'run.readOnlyJournal': '只读持久化 Journal', 'run.queued': '已排队的后续消息：{content}',
  'inspector.title': '检查器', 'inspector.readModel': 'Journal 读模型', 'inspector.wide': '加宽', 'inspector.compact': '紧凑', 'inspector.close': '关闭检查器', 'inspector.trace': '轨迹', 'inspector.context': '上下文', 'inspector.journal': '日志', 'inspector.plugins': '插件', 'inspector.jsonlSource': 'JSONL 数据源', 'inspector.fixtureBlueprint': '原型蓝图',
  'trace.modelCalls': '模型调用', 'trace.facts': '事件', 'trace.toolBatches': '工具批次', 'trace.observed': '观测时长', 'trace.filter': '筛选事件、所属方或内容', 'trace.eventPayload': '事件 / 内容', 'trace.owner': '所属方', 'trace.time': '时间',
  'journal.reading': '正在读取 Journal…', 'journal.readOnly': 'Workbench 以只读方式访问。', 'journal.unavailable': 'Journal 不可用', 'journal.tryAgain': '重试', 'journal.filter': '筛选类型或内容', 'journal.refresh': '刷新', 'journal.noMatch': '没有匹配事件', 'journal.clearFilter': '清除筛选以显示全部事件。',
  'blueprint.label': '蓝图', 'context.description': '投影后的请求形状。只有 Provider 诊断真正需要时才捕获实际请求。', 'context.estimatedTokens': '预估 Token', 'plugins.description': 'Assembly 元数据原型，用于定义未来的读模型契约。', 'plugins.listens': '订阅', 'plugins.emits': '产出', 'plugins.protocols': '协议', 'plugins.author': '作者',
  'studio.loading': '正在加载 Studio…', 'studio.loadingDetail': 'Host 正在读取可用的 Assembly 和案例。', 'studio.realCase': '真实案例', 'studio.noGeneration': '无 Generation', 'studio.checking': '检查中…', 'studio.checked': '已检查', 'studio.checkAssembly': '检查 Assembly', 'studio.publishing': '发布中…', 'studio.publish': '发布 Generation', 'studio.starting': '启动中…', 'studio.runReal': '真实运行', 'studio.tabAssembly': '构建 · Assembly', 'studio.tabPrompt': '构建 · 提示词与工具', 'studio.tabTest': '测试 · 运行与对比', 'studio.tabFlow': '流程 · 声明与观测', 'studio.declaredFlow': '声明拓扑', 'studio.declaredFlowDescription': '由已安装插件声明推导的可能协议路径；此视图不会执行 Assembly。', 'studio.observedFlow': '观测序列', 'studio.observedFlowDescription': '来自一次真实 Run Journal 的事实序列，并标注声明的生产方和订阅方。', 'studio.loadingFlow': '正在加载 Run Journal…', 'studio.registrationOrder': '声明的注册顺序', 'studio.registrationDescription': 'Host 维护的 Assembly 元数据。发布前由 Check Assembly 验证这份固定来源。', 'studio.noSubscriptions': '无订阅', 'studio.assemblyPlugins': 'Assembly 插件', 'studio.pluginsDescription': '职责和协议来自 Host 读模型，而不是浏览器原型数据。', 'studio.declared': '已声明', 'studio.source': '源码', 'studio.stablePrompt': '稳定系统提示词', 'studio.promptDescription': '这里展示配置的提示词来源；具体 Run 的投影结果仍是最终依据。', 'studio.chars': '{count} 字符', 'studio.nativeTools': '原生工具', 'studio.toolsDescription': '工具 Schema 由当前 Assembly 实际安装，Studio 展示其身份和用途。', 'studio.protocolVocabulary': '协议词汇表', 'studio.caseInput': '案例输入', 'studio.caseInputDescription': 'Mock 与 Real 使用同一工作区、请求、断言和当前 Generation。', 'studio.workspace': '工作区', 'studio.userRequest': '用户请求', 'studio.journalAssertions': 'Journal 断言', 'studio.runningMock': 'Mock 运行中…', 'studio.runMock': '运行 Mock 案例', 'studio.startingReal': '真实运行启动中…', 'studio.runRealCase': '运行真实案例', 'studio.assemblyCheck': 'Assembly 检查', 'studio.checkDescription': '静态检查不会调用模型，也不会执行案例。', 'studio.passed': '通过', 'studio.failed': '失败', 'studio.checkBeforePublish': '发布前请先成功执行 Check Assembly。', 'studio.activeGeneration': '当前 Generation', 'studio.generationBoundary': 'Generation 固定 Assembly 身份和指纹；可执行制品导出尚未实现。', 'studio.caseRuns': '案例运行记录', 'studio.runsDescription': 'Mock 和 Real 使用当前 Assembly 边界；指标从各自 Journal 推导。', 'studio.runs': '{count} 次运行', 'studio.noRuns': '尚无运行证据。', 'studio.modeStatus': '模式 / 状态', 'studio.generation': 'Generation', 'studio.calls': '调用', 'studio.tokens': 'Token', 'studio.assertions': '断言', 'studio.modelTools': '{models} 次模型 · {tools} 次工具', 'studio.openTrace': '打开轨迹',
  'dialog.project': '项目', 'dialog.studio': '工作室', 'dialog.create': '新建', 'dialog.newSession': '新建会话', 'dialog.newCase': '新建 Studio 案例', 'dialog.projects': '项目', 'dialog.settings': '项目设置', 'dialog.library': '组件库', 'dialog.untitledProject': '未命名智能体项目', 'dialog.untitledCase': '未命名案例', 'dialog.sessionTitle': '会话标题', 'dialog.workingDirectory': '工作目录', 'dialog.providerProfile': 'Provider 配置', 'dialog.addProvider': '添加本地 Provider 配置', 'dialog.providerAdapter': '适配器', 'dialog.providerLabel': '显示名称', 'dialog.baseUrl': 'Base URL', 'dialog.apiKey': 'API Key', 'dialog.contextWindow': '上下文窗口（可选）', 'dialog.saveProvider': '保存 Provider', 'dialog.providerSecretHint': '密钥仅保存在本地 Host 配置中，不会返回浏览器。', 'dialog.notConfigured': '未配置', 'dialog.reasoningEffort': '推理强度', 'dialog.providerDefault': '使用 Provider 默认值', 'dialog.toolApproval': '工具审批', 'dialog.approvalAsk': 'write、edit 和 bash 执行前询问', 'dialog.approvalAuto': '自动批准所有工具（不安全）', 'dialog.assembly': 'Assembly', 'dialog.model': '模型', 'dialog.noProvider': '没有已配置 Provider', 'dialog.reasoning': '推理', 'dialog.approval': '审批', 'dialog.cancel': '取消', 'dialog.createSession': '创建会话', 'dialog.caseName': '案例名称', 'dialog.caseDescription': '使用当前 Project 的 Assembly、工作区、默认请求和 Journal 断言创建持久化案例。', 'dialog.createCase': '创建案例', 'dialog.newFixtureProject': '新建项目', 'dialog.projectName': '项目名称', 'dialog.workspaceRoot': '项目根目录', 'dialog.createProject': '创建项目', 'dialog.projectRoot': '项目根目录', 'dialog.runtime': '运行时', 'dialog.runtimeValue': '本地 Node.js · 已连接', 'dialog.storage': '存储', 'dialog.storageValue': 'Append-only JSONL', 'dialog.defaultCase': '默认案例', 'dialog.done': '完成', 'dialog.alreadyAssembled': '已装配', 'dialog.libraryDescription': '动态安装仍未实现；当前真实 Studio 发布的是带指纹的 Generation。',
  'error.streamDisconnected': '实时会话连接已断开；已提交事件仍可用。', 'project.localFixture': '本地原型项目',
  'dialog.runSuffix': '运行',
  'status.idle': '空闲', 'status.running': '运行中', 'status.paused': '已暂停', 'status.completed': '已完成', 'status.failed': '失败',
}
